apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    arch: inner
spec:
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      nodeSelector:
        app: keywe-service
      containers:
        - name: admin-service
          image: sunwoo11/keywe_admin_service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 60002
            - containerPort: 50002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_PROFILES_INCLUDE
              value: "actuator,swagger,redis,datasource"
            - name: TZ
              value: Asia/Seoul
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-password
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-port
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-pass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: adm-db-name
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: jwt-access-token-secret
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: jwt-refresh-token-secret
            - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: jwt-access-token-expiration-time
            - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: jwt-refresh-token-expiration-time
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: admin-redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: admin-redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: admin-redis-password
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: admin-service-port
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: admin-grpc-port
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    arch: inner
    istio: sidecar
spec:
  selector:
    app: admin-service
  ports:
    - port: 60002
      targetPort: 60002
      name: http
    - port: 50002
      targetPort: 50002
      name: grpc


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60