apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.47.2
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClass: gp3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
        nodeSelector:
          role: monitoring
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        retention:
          time: 72h
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.15.5
    helm:
      values: |
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
        promtail:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
