apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: did-agent
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "sunwoo11/keywe_did_agent:dev"
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
    argocd.argoproj.io/sync-wave: "4"    
spec:
  project: default
  source:
    repoURL: https://github.com/TeamDoubleO/infra-cd.git
    targetRevision: develop
    path: apps/services/did-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
